frontend_address: ":5000"
api_port: "8080"
peer_port: "8081"
cluster_dns: "lb-cluster.example.com"
node_id: "node1"
frontend_dns: "loadbalancer.example.com"
initial_peers:
  - address: "node2.example.com:8081"
    node_id: "node2"
  - address: "node3.example.com:8081"
    node_id: "node3"
backends:
  - address: "backend1.example.com:80"
    protocol: "http"
    port: 80
    weight: 1
  - address: "backend2.example.com:443"
    protocol: "https"
    port: 443
    weight: 1
  - address: "db1.example.com:5432"
    protocol: "postgresql"
    port: 5432
    weight: 1
  - address: "db2.example.com:3306"
    protocol: "mysql"
    port: 3306
    weight: 1
tls_config:
  enabled: true
  cert_file: "/path/to/cert.pem"
  key_file: "/path/to/key.pem"
  http2: true
  http3: true
cache_config:
  enabled: true
  expiration: 300
